import React from 'react';

export const TermsOfService: React.FC = () => {
  return (
    <div className="space-y-12 py-12 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto text-gray-300 text-xs leading-relaxed">
      <div className="space-y-3 text-center border-b border-[#272E1B] pb-8">
        <h1 className="text-3xl sm:text-4xl font-black text-white">Terms of Service</h1>
        <p className="text-gray-400 text-xs max-w-xl mx-auto">
          Last updated: September 2026. Please read these terms carefully before using the GYMTwiq platform.
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">1. Agreement to Terms</h2>
        <p>
          By creating an account, downloading the GYMTwiq mobile application, or accessing the website, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">2. Network Portability & Access Rules</h2>
        <p>
          GYMTwiq facilitates portable access to independent verified fitness facilities. Each partner gym sets its own house rules, dress codes, and operating hours. Members are required to abide by all partner facility rules during their workout sessions.
        </p>
        <p>
          Turnstile entry requires scanning the designated facility QR code using the official mobile app. Sharing QR codes, check-in credentials, or attempting fraudulent duplicate entries is strictly prohibited.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">3. Wallet, Negative Limits & Subscriptions</h2>
        <p>
          Active network passes grant access to partner facilities. Wallet debits are calculated according to each partner gym’s verified daily rate or selected activity zones.
        </p>
        <p>
          GYMTwiq provides a safety negative wallet limit of -₹500.00 to prevent access interruption. Users agree to settle negative balances via wallet top-up before subscription renewal or cancellation.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">4. GYMTwiq Coins</h2>
        <p>
          GYMTwiq Coins are loyalty points awarded for workout streak consistency. Coins have no direct cash value, cannot be transferred or exchanged for real currency, and expire independently based on lot validity rules.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">5. AI Advisory Disclaimer</h2>
        <p>
          Workout routines and activity recommendations generated by our Gemini AI integration are purely informational suggestions. They do not constitute medical, clinical, or specialized professional advice. Always consult with a certified fitness or healthcare professional before beginning a rigorous exercise program.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-bold text-white uppercase tracking-wider">6. Limitation of Liability</h2>
        <p>
          GYMTwiq provides the technology platform connecting members with partner gyms. GYMTwiq is not liable for personal injury, property loss, or facility equipment failures occurring on partner gym premises.
        </p>
      </section>
    </div>
  );
};
